[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet = "FKPeufJiRLPLvk2d1XbaG9N568JMKYwzBjDuUZE1pjhR"
puppet-master = "2VcxeD66wzXGxGgrQB2YNXHy5y91HESMeV6vouWonq7P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
